# Generated by Django 2.0.5 on 2018-05-25 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orientacion', '0002_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='area_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orientacion.Area'),
            preserve_default=False,
        ),
    ]
